spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: ba2d6934-2cf9-40ea-a4a6-3663ea59e587
            client-secret: ~M.0E_BNMR~V6rQdcxrt6Z4DL~iro0X0_A
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/azure-client'
            scope: openid,profile
          google:
            client-id: 569651838707-kqj5s6fj0124ev2s6k661iekjgarbtsa.apps.googleusercontent.com
            client-secret: _bnEVcaEhBB88kfNWX6wNxEY

server:
  use-forward-headers: true
  forward-headers-strategy: native

