INSERT INTO OccupationalCodeList VALUES (1, "Business and Financial Operations");
INSERT INTO OccupationalCodeList VALUES (2, "Computer and Mathematical");
INSERT INTO OccupationalCodeList VALUES (3, "Architecture and Engineering");
INSERT INTO OccupationalCodeList VALUES (4, "Life, Physical, and Social Science");
INSERT INTO OccupationalCodeList VALUES (5, "Community and Social Service");
INSERT INTO OccupationalCodeList VALUES (6, "Legal");
INSERT INTO OccupationalCodeList VALUES (7, "Educational Instruction and Library");
INSERT INTO OccupationalCodeList VALUES (8, "Arts, Design, Entertainment, Sports, and Media");
INSERT INTO OccupationalCodeList VALUES (9, "Healthcare Practitioners and Technical");
INSERT INTO OccupationalCodeList VALUES (10, "Healthcare Support");
INSERT INTO OccupationalCodeList VALUES (11, "Protective Service");
INSERT INTO OccupationalCodeList VALUES (12, "Food Preparation and Serving Related");
INSERT INTO OccupationalCodeList VALUES (13, "Building and Grounds Cleaning and Maintenance");
INSERT INTO OccupationalCodeList VALUES (14, "Personal Care and Service");
INSERT INTO OccupationalCodeList VALUES (15, "Sales and Related");
INSERT INTO OccupationalCodeList VALUES (16, "Office and Administrative Support");
INSERT INTO OccupationalCodeList VALUES (17, "Farming, Fishing, and Forestry");
INSERT INTO OccupationalCodeList VALUES (18, "Construction and Extraction");
INSERT INTO OccupationalCodeList VALUES (19, "Installation, Maintenance, and Repair");
INSERT INTO OccupationalCodeList VALUES (20, "Production");
INSERT INTO OccupationalCodeList VALUES (21, "Transportation and Material Moving");
INSERT INTO OccupationalCodeList VALUES (22, "Military Specific");