INSERT INTO LocalAuthorityList VALUES (1, "Caerphilly");
INSERT INTO LocalAuthorityList VALUES (2, "Ceredigion");
INSERT INTO LocalAuthorityList VALUES (3, "Flintshire");
INSERT INTO LocalAuthorityList VALUES (4, "Merthyr Tydfil");
INSERT INTO LocalAuthorityList VALUES (5, "Newport");
INSERT INTO LocalAuthorityList VALUES (6, "Rhondda Cynon Taf");
INSERT INTO LocalAuthorityList VALUES (7, "Vale of Glamorgan");
INSERT INTO LocalAuthorityList VALUES (8, "Bridgend");
INSERT INTO LocalAuthorityList VALUES (9, "Carmarthenshire");
INSERT INTO LocalAuthorityList VALUES (10, "Denbigshire");
INSERT INTO LocalAuthorityList VALUES (11, "Isle of Anglesey");
INSERT INTO LocalAuthorityList VALUES (12, "Neath Port Talbot");
INSERT INTO LocalAuthorityList VALUES (13, "Powys");
INSERT INTO LocalAuthorityList VALUES (14, "Torfaen");
INSERT INTO LocalAuthorityList VALUES (15, "Blaenau Gwent");
INSERT INTO LocalAuthorityList VALUES (16, "Cardiff");
INSERT INTO LocalAuthorityList VALUES (17, "Conwy");
INSERT INTO LocalAuthorityList VALUES (18, "Gwynedd");
INSERT INTO LocalAuthorityList VALUES (19, "Monmountshire");
INSERT INTO LocalAuthorityList VALUES (20, "Pembrokshire");
INSERT INTO LocalAuthorityList VALUES (21, "Swansea");
INSERT INTO LocalAuthorityList VALUES (22, "Wrexham");
