INSERT INTO OccupationalCodesList VALUES (1, "Business and Financial Operations");
INSERT INTO OccupationalCodesList VALUES (2, "Computer and Mathematical");
INSERT INTO OccupationalCodesList VALUES (3, "Architecture and Engineering");
INSERT INTO OccupationalCodesList VALUES (4, "Life, Physical, and Social Science");
INSERT INTO OccupationalCodesList VALUES (5, "Community and Social Service");
INSERT INTO OccupationalCodesList VALUES (6, "Legal");
INSERT INTO OccupationalCodesList VALUES (7, "Educational Instruction and Library");
INSERT INTO OccupationalCodesList VALUES (8, "Arts, Design, Entertainment, Sports, and Media");
INSERT INTO OccupationalCodesList VALUES (9, "Healthcare Practitioners and Technical");
INSERT INTO OccupationalCodesList VALUES (10, "Healthcare Support");
INSERT INTO OccupationalCodesList VALUES (11, "Protective Service");
INSERT INTO OccupationalCodesList VALUES (12, "Food Preparation and Serving Related");
INSERT INTO OccupationalCodesList VALUES (13, "Building and Grounds Cleaning and Maintenance");
INSERT INTO OccupationalCodesList VALUES (14, "Personal Care and Service");
INSERT INTO OccupationalCodesList VALUES (15, "Sales and Related");
INSERT INTO OccupationalCodesList VALUES (16, "Office and Administrative Support");
INSERT INTO OccupationalCodesList VALUES (17, "Farming, Fishing, and Forestry");
INSERT INTO OccupationalCodesList VALUES (18, "Construction and Extraction");
INSERT INTO OccupationalCodesList VALUES (19, "Installation, Maintenance, and Repair");
INSERT INTO OccupationalCodesList VALUES (20, "Production");
INSERT INTO OccupationalCodesList VALUES (21, "Transportation and Material Moving");
INSERT INTO OccupationalCodesList VALUES (22, "Military Specific");